class Grid:

    def __init__(self):
        self.generated = 0.0
        self.demanded = 0.0
        self.utilized = 0.0

    def setValues(self, generated, demanded, utilized):
        self.generated = generated
        self.demanded = demanded
        self.utilized = utilized

print("Smart contract")
# ============================

print("Total micro Grids : 2")
print("1st grid")
mg1 = Grid()
print("Enter following details")
print("Power Generated by 1st grid")
generated = int(input())
print("Power demanded by 1st grid")
demanded = int(input())
print("Power utilized by 1st grid")
utilized = int(input())
mg1.setValues(generated=generated, demanded=demanded, utilized=utilized)

print("2nd grid")
mg2 = Grid()
print("Enter following details")
print("Power Generated by 2nd grid")
generated = int(input())
print("Power demanded by 2nd grid")
demanded = int(input())
print("Power utilized by 2nd grid")
utilized = int(input())
mg2.setValues(generated=generated, demanded=demanded, utilized=utilized)

print("Power Grid specification")
print("Micro Grid 1")
print("Power Generated : ", mg1.generated)
print("Power Demanded : ", mg1.demanded)
print("Power Utilized : ", mg1.utilized)

print("Micro Grid 2")
print("Power Generated : ", mg2.generated)
print("Power Demanded : ", mg2.demanded)
print("Power Utilized : ", mg2.utilized)

if mg1.generated > mg1.demanded:
    print("Possible power Seller")
if mg1.generated < mg1.demanded:
    print("Possible power Buyer")

print()
if mg2.generated > mg2.demanded:
    print("Possible power Seller")
if mg2.generated < mg2.demanded:
    print("Possible power Buyer")

print("Smart Contract Guidelines")
print("1. Electrical Guidelines")
print("2. Business Guidelines")

print("Enter votage profile for grid1 :")
mg1_volt_profile = float(input())
print("Enter frequency for grid1 :")
mg1_frequency = float(input())

print("Enter votage profile for grid2 :")
mg2_volt_profile = float(input())
print("Enter frequency for grid2 :")
mg2_frequency = float(input())

if mg1_volt_profile == mg2_volt_profile:
    if mg1_frequency == mg2_frequency:
        print("Smart contract is successful")
    else:
        print("Smart contract is not successful")
else:
    print("Smart contract is not successful")